# Generated by Django 2.2.7 on 2020-03-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200314_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
