# Generated by Django 2.2.7 on 2020-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200314_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='general_access',
            field=models.CharField(choices=[('common', 'Обычный'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='common', max_length=50, verbose_name='Общий доступ'),
        ),
    ]
